"""Add funnel fields to scripts and conversations

Revision ID: 20260615_funnel_fields
Revises: 9fbbddc0c495
Create Date: 2026-06-15 11:30:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260615_funnel_fields'
down_revision: Union[str, None] = '9fbbddc0c495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('sales_funnel', sa.JSON(), nullable=True))
    op.add_column('scripts', sa.Column('first_message_goal', sa.String(length=20), nullable=True))
    op.add_column('scripts', sa.Column('call_to_action', sa.String(length=200), nullable=True))
    op.add_column('scripts', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('scripts', sa.Column('emoji_policy', sa.String(length=20), nullable=True))
    op.add_column('scripts', sa.Column('max_first_message_length', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('conversation_stage', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'conversation_stage')
    op.drop_column('scripts', 'max_first_message_length')
    op.drop_column('scripts', 'emoji_policy')
    op.drop_column('scripts', 'language')
    op.drop_column('scripts', 'call_to_action')
    op.drop_column('scripts', 'first_message_goal')
    op.drop_column('scripts', 'sales_funnel')
    # ### end Alembic commands ###
