"""Initial migration

Revision ID: 9fbbddc0c495
Revises: 
Create Date: 2026-06-08 15:42:54

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fbbddc0c495'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('role_prompt', sa.Text(), nullable=False),
        sa.Column('target_audience', sa.Text(), nullable=True),
        sa.Column('goal', sa.Text(), nullable=False),
        sa.Column('success_criteria', sa.Text(), nullable=True),
        sa.Column('tone', sa.String(length=20), nullable=True),
        sa.Column('max_messages', sa.Integer(), nullable=True),
        sa.Column('follow_up_delay_hours', sa.Integer(), nullable=True),
        sa.Column('working_hours_start', sa.Time(), nullable=True),
        sa.Column('working_hours_end', sa.Time(), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_accounts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('session_string', sa.Text(), nullable=True),
        sa.Column('display_name', sa.String(length=100), nullable=True),
        sa.Column('username', sa.String(length=32), nullable=True),
        sa.Column('bio', sa.Text(), nullable=True),
        sa.Column('avatar_url', sa.Text(), nullable=True),
        sa.Column('proxy_url', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('daily_messages_sent', sa.Integer(), nullable=True),
        sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone')
    )
    op.create_table('contacts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('telegram_username', sa.String(length=32), nullable=True),
        sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('first_name', sa.String(length=100), nullable=True),
        sa.Column('last_name', sa.String(length=100), nullable=True),
        sa.Column('company_name', sa.String(length=200), nullable=True),
        sa.Column('position', sa.String(length=100), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.Column('icp_score', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('assigned_script_id', sa.UUID(), nullable=True),
        sa.Column('assigned_account_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['assigned_script_id'], ['scripts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('script_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('total_contacts', sa.Integer(), nullable=True),
        sa.Column('processed_contacts', sa.Integer(), nullable=True),
        sa.Column('replied_count', sa.Integer(), nullable=True),
        sa.Column('qualified_count', sa.Integer(), nullable=True),
        sa.Column('meeting_booked_count', sa.Integer(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_contacts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('campaign_id', sa.UUID(), nullable=True),
        sa.Column('contact_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('initial_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reply_received_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('message_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('contact_id', sa.UUID(), nullable=True),
        sa.Column('campaign_id', sa.UUID(), nullable=True),
        sa.Column('current_state', sa.String(length=20), nullable=True),
        sa.Column('sentiment', sa.String(length=20), nullable=True),
        sa.Column('facts_extracted', sa.JSON(), nullable=True),
        sa.Column('operator_status', sa.String(length=20), nullable=True),
        sa.Column('operator_notes', sa.Text(), nullable=True),
        sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('conversation_id', sa.UUID(), nullable=True),
        sa.Column('direction', sa.String(length=10), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('message_type', sa.String(length=20), nullable=True),
        sa.Column('intent_classification', sa.String(length=50), nullable=True),
        sa.Column('llm_model', sa.String(length=50), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('typing_delay_ms', sa.Integer(), nullable=True),
        sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('campaign_contacts')
    op.drop_table('campaigns')
    op.drop_table('contacts')
    op.drop_table('telegram_accounts')
    op.drop_table('scripts')
    # ### end Alembic commands ###
